Offline adjustments
google/megalista pull request #142
Opened 2023-04-25 17:24 UTC by cymbaum

Adds Offline Conversion Adjustments functionality

2023-05-03 21:56 UTC, Mr-Lopes requested changes
Thank you for this! I've added a few comments and I also noticed that two unit tests are broken. Could you check?

2023-05-03 21:56 UTC, Mr-Lopes commented on megalista_dataflow/data_sources/big_query/big_query_data_source.py
> +            return SchemaField("order_id", "string"), SchemaField("timestamp", "timestamp")
Add time column if necessary (comments above)

2023-05-05 20:37 UTC, cymbaum commented on megalista_dataflow/data_sources/big_query/big_query_data_source.py
> +                    retry=Retry(deadline=120)))
do you mean (utils.py#L96)? 
I believe it is not called here in the insert_rows from the BQ client. This retry is preventing some transient errors described here: https://github.com/googleapis/python-bigquery/issues/1331
The retry + backoff seemed to resolve the issue.

2023-05-05 21:35 UTC, cymbaum commented on megalista_dataflow/data_sources/big_query/big_query_data_source.py
> +                                LEFT JOIN `$uploaded_table_name` AS uploaded USING(order_id) \
Done.

2023-05-05 21:35 UTC, cymbaum commented on megalista_dataflow/data_sources/big_query/big_query_data_source.py
> +                            order_id STRING OPTIONS(description= 'Order Id (transaction Id)')) \
Done.

2023-05-05 21:35 UTC, cymbaum commented on megalista_dataflow/data_sources/big_query/big_query_data_source.py
> +            return SchemaField("order_id", "string"), SchemaField("timestamp", "timestamp")
Done.

2023-05-05 21:35 UTC, cymbaum commented on megalista_dataflow/data_sources/big_query/big_query_data_source.py
> +            return [{'order_id': row['order_id'], 'timestamp': now} for row in rows]
Done.

2023-05-05 21:35 UTC, cymbaum commented on megalista_dataflow/data_sources/data_schemas.py
> +            {'name': 'amount', 'required': False, 'data_type': 'string'}
Done.

2023-05-05 21:36 UTC, cymbaum commented on megalista_dataflow/data_sources/data_schemas.py
> +            {'name': 'amount', 'required': False, 'data_type': 'string'}
Done.

2023-05-05 21:36 UTC, cymbaum commented on megalista_dataflow/uploaders/google_ads/conversions/google_ads_offline_conversion_adjustments_uploader.py
> +    @utils.safe_process(logger=logging.getLogger('megalista.GoogleAdsOfflineUploader'))
Done. Thanks :)

2023-05-09 21:09 UTC, Mr-Lopes requested changes
Please see comments

2023-06-07 19:20 UTC, Mr-Lopes approved these changes
LGTM

2023-06-07 19:22 UTC, merged